"""
Test BMfast Python implementation against R reference results.

This test compares the Python Brunner-Munzel implementation with
results generated from the R LESYMAP package (BMfast2 function).
"""

import numpy as np
import pandas as pd
from pathlib import Path
import sys

# Add the lesymap-python package to the path
sys.path.insert(0, str(Path(__file__).parent.parent / "lesymap-python" / "lesymap"))

def load_r_reference_data():
    """Load reference data generated by R LESYMAP."""
    fixtures_dir = Path(__file__).parent / "fixtures" / "r_reference_results"

    # Load lesion matrix
    lesmat_df = pd.read_csv(fixtures_dir / "bmfast_lesmat.csv")
    lesmat = lesmat_df.values.astype(np.float64)

    # Load behavior
    behavior_df = pd.read_csv(fixtures_dir / "bmfast_behavior.csv")
    behavior = behavior_df["behavior"].values.astype(np.float64)

    # Load R results
    results_df = pd.read_csv(fixtures_dir / "bmfast_results.csv")
    r_statistic = results_df["statistic"].values
    r_dfbm = results_df["dfbm"].values
    r_pvalue = results_df["pvalue_twosided"].values

    return lesmat, behavior, r_statistic, r_dfbm, r_pvalue


def test_bmfast_against_r():
    """Compare Python BMfast with R BMfast2 reference."""
    from stats_compiled.bm import brunner_munzel_fast
    from scipy import stats

    # Load reference data
    lesmat, behavior, r_statistic, r_dfbm, r_pvalue = load_r_reference_data()

    print(f"Test data: {lesmat.shape[0]} subjects, {lesmat.shape[1]} voxels")
    print(f"Behavior range: [{behavior.min():.2f}, {behavior.max():.2f}]")

    # Run Python implementation
    py_statistic, py_dfbm = brunner_munzel_fast(lesmat, behavior, compute_dof=True)

    # Compute p-values (two-tailed)
    py_pvalue = 2 * (1 - stats.t.cdf(np.abs(py_statistic), py_dfbm))

    # Compare statistics
    stat_diff = np.abs(py_statistic - r_statistic)
    stat_rel_diff = stat_diff / (np.abs(r_statistic) + 1e-10)

    print("\n=== STATISTIC COMPARISON ===")
    print(f"R statistic range: [{r_statistic.min():.6f}, {r_statistic.max():.6f}]")
    print(f"Python statistic range: [{py_statistic.min():.6f}, {py_statistic.max():.6f}]")
    print(f"Max absolute difference: {stat_diff.max():.10f}")
    print(f"Max relative difference: {stat_rel_diff.max():.10f}")
    print(f"Mean absolute difference: {stat_diff.mean():.10f}")

    # Compare degrees of freedom
    df_diff = np.abs(py_dfbm - r_dfbm)
    df_rel_diff = df_diff / (np.abs(r_dfbm) + 1e-10)

    print("\n=== DEGREES OF FREEDOM COMPARISON ===")
    print(f"R DOF range: [{r_dfbm.min():.6f}, {r_dfbm.max():.6f}]")
    print(f"Python DOF range: [{py_dfbm.min():.6f}, {py_dfbm.max():.6f}]")
    print(f"Max absolute difference: {df_diff.max():.10f}")
    print(f"Max relative difference: {df_rel_diff.max():.10f}")
    print(f"Mean absolute difference: {df_diff.mean():.10f}")

    # Compare p-values
    pval_diff = np.abs(py_pvalue - r_pvalue)
    pval_rel_diff = pval_diff / (np.abs(r_pvalue) + 1e-10)

    print("\n=== P-VALUE COMPARISON ===")
    print(f"R p-value range: [{r_pvalue.min():.6f}, {r_pvalue.max():.6f}]")
    print(f"Python p-value range: [{py_pvalue.min():.6f}, {py_pvalue.max():.6f}]")
    print(f"Max absolute difference: {pval_diff.max():.10f}")
    print(f"Max relative difference: {pval_rel_diff.max():.10f}")
    print(f"Mean absolute difference: {pval_diff.mean():.10f}")

    # Print first 5 comparisons
    print("\n=== FIRST 5 VOXEL COMPARISONS ===")
    print(f"{'Voxel':<8} {'R Stat':<12} {'Py Stat':<12} {'R DOF':<10} {'Py DOF':<10} {'R pval':<10} {'Py pval':<10}")
    print("-" * 80)
    for i in range(min(5, len(r_statistic))):
        print(f"{i:<8} {r_statistic[i]:<12.6f} {py_statistic[i]:<12.6f} {r_dfbm[i]:<10.4f} {py_dfbm[i]:<10.4f} {r_pvalue[i]:<10.6f} {py_pvalue[i]:<10.6f}")

    # Check tolerances
    STAT_TOLERANCE = 1e-6
    DOF_TOLERANCE = 1e-6
    PVAL_TOLERANCE = 1e-6

    stat_pass = stat_rel_diff.max() < STAT_TOLERANCE
    dof_pass = df_rel_diff.max() < DOF_TOLERANCE
    pval_pass = pval_rel_diff.max() < PVAL_TOLERANCE

    print("\n=== TEST RESULTS ===")
    print(f"Statistic match (tol={STAT_TOLERANCE}): {'PASS' if stat_pass else 'FAIL'}")
    print(f"DOF match (tol={DOF_TOLERANCE}): {'PASS' if dof_pass else 'FAIL'}")
    print(f"P-value match (tol={PVAL_TOLERANCE}): {'PASS' if pval_pass else 'FAIL'}")

    return stat_pass and dof_pass and pval_pass


if __name__ == "__main__":
    success = test_bmfast_against_r()
    sys.exit(0 if success else 1)
