"""
Test Python regression implementation against R reference data.

This test validates that the Python regression_fast() function produces
results matching the R regresfast() function from LESYMAP.
"""

import numpy as np
import pandas as pd
import pytest
from pathlib import Path
from scipy import stats

import sys
sys.path.insert(0, str(Path(__file__).parent.parent / "lesymap-python"))

from lesymap.stats_compiled.regression import regression_fast


# Path to R reference data
FIXTURES_DIR = Path(__file__).parent / "fixtures" / "r_reference_results"


class TestRegressionRComparison:
    """Test regression_fast against R reference implementation."""

    @pytest.fixture
    def r_reference_data(self):
        """Load R reference data generated by generate_r_regression_reference.R"""
        lesmat = pd.read_csv(FIXTURES_DIR / "regression_lesmat.csv").values
        behavior = pd.read_csv(FIXTURES_DIR / "regression_behavior.csv")["behavior"].values
        results = pd.read_csv(FIXTURES_DIR / "regression_results.csv")

        return {
            "lesmat": lesmat,
            "behavior": behavior,
            "t_statistic": results["t_statistic"].values,
            "p_value": results["p_value"].values,
            "z_score": results["z_score"].values,
        }

    def test_regression_t_statistics_match_r(self, r_reference_data):
        """Test that Python t-statistics match R reference values."""
        lesmat = r_reference_data["lesmat"].astype(np.float64)
        behavior = r_reference_data["behavior"].astype(np.float64)
        r_t_stats = r_reference_data["t_statistic"]

        # Run Python regression
        py_t_stats, n_subjects, kxmat = regression_fast(lesmat, behavior)

        # Compare t-statistics
        tolerance = 1e-6
        max_diff = np.max(np.abs(py_t_stats - r_t_stats))

        print(f"\n{'='*60}")
        print("Regression T-Statistics Comparison: Python vs R")
        print(f"{'='*60}")
        print(f"Number of subjects: {n_subjects}")
        print(f"Number of voxels: {len(py_t_stats)}")
        print(f"Number of predictors (kxmat): {kxmat}")
        print(f"\nR t-statistic range: [{r_t_stats.min():.6f}, {r_t_stats.max():.6f}]")
        print(f"Python t-statistic range: [{py_t_stats.min():.6f}, {py_t_stats.max():.6f}]")
        print(f"\nMaximum absolute difference: {max_diff:.2e}")
        print(f"Tolerance: {tolerance:.2e}")

        # Show first 10 comparisons
        print(f"\nFirst 10 t-statistics comparison:")
        print(f"{'Voxel':<8} {'R':>15} {'Python':>15} {'Diff':>15}")
        print("-" * 53)
        for i in range(min(10, len(py_t_stats))):
            diff = py_t_stats[i] - r_t_stats[i]
            print(f"{i+1:<8} {r_t_stats[i]:>15.6f} {py_t_stats[i]:>15.6f} {diff:>15.2e}")

        # Assert match within tolerance
        if max_diff <= tolerance:
            print(f"\n[PASS] All t-statistics match within tolerance {tolerance:.2e}")
        else:
            print(f"\n[FAIL] Maximum difference {max_diff:.2e} exceeds tolerance {tolerance:.2e}")

        np.testing.assert_allclose(
            py_t_stats, r_t_stats, rtol=tolerance, atol=tolerance,
            err_msg="Python t-statistics do not match R reference values"
        )

    def test_regression_pvalues_match_r(self, r_reference_data):
        """Test that Python p-values match R reference values."""
        lesmat = r_reference_data["lesmat"].astype(np.float64)
        behavior = r_reference_data["behavior"].astype(np.float64)
        r_pvals = r_reference_data["p_value"]

        # Run Python regression
        py_t_stats, n_subjects, kxmat = regression_fast(lesmat, behavior)

        # Compute two-sided p-values (matching R implementation)
        # R: pvalue = pt( abs(statistic) * -1, temp$n - temp$kxmat, lower.tail = T, log.p = F) * 2
        df = n_subjects - kxmat
        py_pvals = stats.t.cdf(-np.abs(py_t_stats), df) * 2

        # Compare p-values
        tolerance = 1e-6
        max_diff = np.max(np.abs(py_pvals - r_pvals))

        print(f"\n{'='*60}")
        print("Regression P-Values Comparison: Python vs R")
        print(f"{'='*60}")
        print(f"Degrees of freedom: {df}")
        print(f"\nR p-value range: [{r_pvals.min():.6f}, {r_pvals.max():.6f}]")
        print(f"Python p-value range: [{py_pvals.min():.6f}, {py_pvals.max():.6f}]")
        print(f"\nMaximum absolute difference: {max_diff:.2e}")
        print(f"Tolerance: {tolerance:.2e}")

        # Show first 10 comparisons
        print(f"\nFirst 10 p-values comparison:")
        print(f"{'Voxel':<8} {'R':>15} {'Python':>15} {'Diff':>15}")
        print("-" * 53)
        for i in range(min(10, len(py_pvals))):
            diff = py_pvals[i] - r_pvals[i]
            print(f"{i+1:<8} {r_pvals[i]:>15.6f} {py_pvals[i]:>15.6f} {diff:>15.2e}")

        # Assert match within tolerance
        if max_diff <= tolerance:
            print(f"\n[PASS] All p-values match within tolerance {tolerance:.2e}")
        else:
            print(f"\n[FAIL] Maximum difference {max_diff:.2e} exceeds tolerance {tolerance:.2e}")

        np.testing.assert_allclose(
            py_pvals, r_pvals, rtol=tolerance, atol=tolerance,
            err_msg="Python p-values do not match R reference values"
        )

    def test_regression_dimensions(self, r_reference_data):
        """Test that regression returns correct dimensions."""
        lesmat = r_reference_data["lesmat"].astype(np.float64)
        behavior = r_reference_data["behavior"].astype(np.float64)

        py_t_stats, n_subjects, kxmat = regression_fast(lesmat, behavior)

        n_subjects_expected, n_voxels = lesmat.shape

        print(f"\n{'='*60}")
        print("Regression Dimensions Check")
        print(f"{'='*60}")
        print(f"Input lesmat shape: {lesmat.shape}")
        print(f"Input behavior length: {len(behavior)}")
        print(f"Output t-statistics length: {len(py_t_stats)}")
        print(f"Returned n_subjects: {n_subjects}")
        print(f"Returned kxmat: {kxmat}")

        assert len(py_t_stats) == n_voxels, f"Expected {n_voxels} t-statistics, got {len(py_t_stats)}"
        assert n_subjects == n_subjects_expected, f"Expected {n_subjects_expected} subjects, got {n_subjects}"
        assert kxmat == 2, f"Expected kxmat=2 (intercept + lesion), got {kxmat}"

        print("\n[PASS] All dimensions correct")


def test_regression_basic():
    """Basic test that regression runs without errors."""
    np.random.seed(42)
    X = np.random.randint(0, 2, size=(20, 50)).astype(np.float64)
    y = np.random.randn(20)

    t_stats, n, k = regression_fast(X, y)

    assert len(t_stats) == 50
    assert n == 20
    assert k == 2
    print("\n[PASS] Basic regression test passed")


if __name__ == "__main__":
    # Run tests manually for detailed output
    print("\nRunning Regression R Comparison Tests")
    print("=" * 60)

    # Load reference data
    lesmat = pd.read_csv(FIXTURES_DIR / "regression_lesmat.csv").values.astype(np.float64)
    behavior = pd.read_csv(FIXTURES_DIR / "regression_behavior.csv")["behavior"].values.astype(np.float64)
    results = pd.read_csv(FIXTURES_DIR / "regression_results.csv")

    r_t_stats = results["t_statistic"].values
    r_pvals = results["p_value"].values

    # Run Python regression
    py_t_stats, n_subjects, kxmat = regression_fast(lesmat, behavior)

    # Compute p-values
    df = n_subjects - kxmat
    py_pvals = stats.t.cdf(-np.abs(py_t_stats), df) * 2

    # Compare t-statistics
    t_stat_diff = np.max(np.abs(py_t_stats - r_t_stats))
    pval_diff = np.max(np.abs(py_pvals - r_pvals))

    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    print(f"T-statistics max difference: {t_stat_diff:.2e}")
    print(f"P-values max difference: {pval_diff:.2e}")
    print(f"Tolerance: 1e-6")

    tolerance = 1e-6
    t_pass = t_stat_diff <= tolerance
    p_pass = pval_diff <= tolerance

    print(f"\nT-statistics test: {'PASS' if t_pass else 'FAIL'}")
    print(f"P-values test: {'PASS' if p_pass else 'FAIL'}")
    print(f"\nOverall: {'PASS' if (t_pass and p_pass) else 'FAIL'}")
