"""
Test Python chi-square implementation against R reference data.

This test loads reference data generated by R's chisq.test function
and compares it with Python's scipy.stats.chi2_contingency.
"""

import numpy as np
import pandas as pd
from scipy import stats
from pathlib import Path


def load_r_reference_data():
    """Load R reference data from CSV files."""
    ref_dir = Path(__file__).parent / "fixtures" / "r_reference_results"

    lesmat = pd.read_csv(ref_dir / "chisq_lesmat.csv").values
    behavior = pd.read_csv(ref_dir / "chisq_behavior.csv").values.flatten()
    r_statistic = pd.read_csv(ref_dir / "chisq_statistic.csv").values.flatten()
    r_pvalue = pd.read_csv(ref_dir / "chisq_pvalue.csv").values.flatten()

    return lesmat, behavior, r_statistic, r_pvalue


def compute_python_chisq(lesmat: np.ndarray, behavior: np.ndarray):
    """
    Compute chi-square test using Python (scipy.stats.chi2_contingency).

    Matches R's lsm_chisq implementation structure.
    """
    n_voxels = lesmat.shape[1]
    statistic = np.zeros(n_voxels)
    pvals = np.zeros(n_voxels)

    for vox in range(n_voxels):
        # Build contingency table matching R's structure
        # R builds: lesOnBehavOff, lesOnBehavOn, lesOffBehavOff, lesOffBehavOn
        # as a 2x2 matrix with ncol=2
        les = lesmat[:, vox]

        les_on_behav_on = np.sum((les == 1) & (behavior == 1))
        les_on_behav_off = np.sum((les == 1) & (behavior == 0))
        les_off_behav_on = np.sum((les == 0) & (behavior == 1))
        les_off_behav_off = np.sum((les == 0) & (behavior == 0))

        # R's matrix(c(lesOnBehavOff, lesOnBehavOn, lesOffBehavOff, lesOffBehavOn), ncol=2)
        # fills by column:
        #   col1: lesOnBehavOff, lesOnBehavOn
        #   col2: lesOffBehavOff, lesOffBehavOn
        # So the table is:
        #        behav_off  behav_on
        # les_on    a          b
        # les_off   c          d
        table = np.array([
            [les_on_behav_off, les_on_behav_on],
            [les_off_behav_off, les_off_behav_on]
        ])

        # Chi-square test without Yates correction (correction=False in R)
        try:
            stat, p, dof, expected = stats.chi2_contingency(table, correction=False)
            statistic[vox] = stat
            pvals[vox] = p
        except ValueError:
            statistic[vox] = 0
            pvals[vox] = 1.0

    return statistic, pvals


def test_chisq_against_r_reference():
    """Test Python chi-square against R reference implementation."""
    # Load R reference data
    lesmat, behavior, r_statistic, r_pvalue = load_r_reference_data()

    # Compute Python chi-square
    py_statistic, py_pvalue = compute_python_chisq(lesmat, behavior)

    # Set tolerance
    tol = 1e-6

    # Compare statistics
    stat_diff = np.abs(py_statistic - r_statistic)
    stat_max_diff = np.max(stat_diff)
    stat_pass = stat_max_diff < tol

    # Compare p-values
    pval_diff = np.abs(py_pvalue - r_pvalue)
    pval_max_diff = np.max(pval_diff)
    pval_pass = pval_max_diff < tol

    # Report results
    print("\n" + "=" * 60)
    print("Chi-square Test: Python vs R Comparison")
    print("=" * 60)
    print(f"\nData dimensions: {lesmat.shape[0]} subjects x {lesmat.shape[1]} voxels")
    print(f"Tolerance: {tol}")

    print("\n--- Statistics Comparison ---")
    print(f"Max absolute difference: {stat_max_diff:.2e}")
    print(f"Mean absolute difference: {np.mean(stat_diff):.2e}")
    print(f"PASS: {stat_pass}")

    print("\n--- P-values Comparison ---")
    print(f"Max absolute difference: {pval_max_diff:.2e}")
    print(f"Mean absolute difference: {np.mean(pval_diff):.2e}")
    print(f"PASS: {pval_pass}")

    # Show first 5 comparisons
    print("\n--- First 5 Voxels Comparison ---")
    print(f"{'Voxel':<8} {'R stat':<12} {'Py stat':<12} {'R pval':<12} {'Py pval':<12}")
    print("-" * 56)
    for i in range(5):
        print(f"{i+1:<8} {r_statistic[i]:<12.6f} {py_statistic[i]:<12.6f} "
              f"{r_pvalue[i]:<12.6f} {py_pvalue[i]:<12.6f}")

    print("\n" + "=" * 60)
    overall_pass = stat_pass and pval_pass
    if overall_pass:
        print("OVERALL RESULT: PASS")
    else:
        print("OVERALL RESULT: FAIL")
    print("=" * 60)

    # Assertions for pytest
    assert stat_pass, f"Statistics differ by more than {tol}: max diff = {stat_max_diff}"
    assert pval_pass, f"P-values differ by more than {tol}: max diff = {pval_max_diff}"


if __name__ == "__main__":
    test_chisq_against_r_reference()
