"""
Test SVR implementation comparison between R (e1071) and Python (sklearn).

This test validates that the Python SVR implementation produces results
consistent with the R implementation, accounting for expected differences
between the two libsvm wrappers.

Key differences between R (e1071) and Python (sklearn) SVR:
1. Default parameters differ significantly:
   - R: kernel='radial', cost=30, gamma=5
   - Python: kernel='linear', C=1.0
2. Weight extraction methods are similar but may differ slightly
3. Both use libsvm under the hood, but wrappers may have subtle differences

Reference: Zhang et al. (2015) SVR-LSM methodology
"""

import os
import numpy as np
import pandas as pd
import pytest
from pathlib import Path
from scipy.stats import pearsonr
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

# Get the fixtures directory
FIXTURES_DIR = Path(__file__).parent / "fixtures"


def load_r_reference_data():
    """Load reference data generated by R script."""
    data = {}

    # Load input data
    data['lesmat'] = pd.read_csv(FIXTURES_DIR / "svr_lesmat.csv").values
    data['behavior'] = pd.read_csv(FIXTURES_DIR / "svr_behavior.csv").values.flatten()

    # Load R results with sklearn-like defaults (C=1, linear kernel)
    data['weights_sklearn_defaults'] = pd.read_csv(
        FIXTURES_DIR / "svr_weights_sklearn_defaults.csv"
    ).values.flatten()
    data['predictions_sklearn_defaults'] = pd.read_csv(
        FIXTURES_DIR / "svr_predictions_sklearn_defaults.csv"
    ).values.flatten()

    # Load linear kernel results (C=30)
    data['weights_linear'] = pd.read_csv(
        FIXTURES_DIR / "svr_weights_linear.csv"
    ).values.flatten()
    data['predictions_linear'] = pd.read_csv(
        FIXTURES_DIR / "svr_predictions_linear.csv"
    ).values.flatten()

    # Load scaling parameters
    scaling = pd.read_csv(FIXTURES_DIR / "svr_scaling_params.csv")
    data['behavior_mean'] = scaling['behavior_mean'].values[0]
    data['behavior_sd'] = scaling['behavior_sd'].values[0]

    return data


def check_reference_data_exists():
    """Check if R reference data files exist."""
    required_files = [
        "svr_lesmat.csv",
        "svr_behavior.csv",
        "svr_weights_sklearn_defaults.csv",
        "svr_predictions_sklearn_defaults.csv",
        "svr_weights_linear.csv",
        "svr_predictions_linear.csv",
        "svr_scaling_params.csv",
    ]
    return all((FIXTURES_DIR / f).exists() for f in required_files)


@pytest.mark.skipif(
    not check_reference_data_exists(),
    reason="R reference data not generated. Run generate_r_svr_reference.R first."
)
class TestSVRComparison:
    """Test SVR implementation against R reference."""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Load reference data."""
        self.data = load_r_reference_data()
        self.lesmat = self.data['lesmat']
        self.behavior = self.data['behavior']

        # Scale data as R does
        self.behavior_scaled = (
            self.behavior - np.mean(self.behavior)
        ) / np.std(self.behavior, ddof=0)

        # Scale lesmat column-wise
        self.lesmat_mean = np.mean(self.lesmat, axis=0)
        self.lesmat_std = np.std(self.lesmat, axis=0, ddof=0)
        # Avoid division by zero
        self.lesmat_std[self.lesmat_std == 0] = 1.0
        self.lesmat_scaled = (self.lesmat - self.lesmat_mean) / self.lesmat_std

    def test_predictions_correlation_linear_c1(self):
        """Test that Python SVR predictions correlate highly with R predictions.

        Using sklearn defaults: linear kernel, C=1.
        """
        # Fit Python SVR with same parameters as R sklearn_defaults
        svr = SVR(kernel='linear', C=1.0, epsilon=0.1)
        svr.fit(self.lesmat_scaled, self.behavior_scaled)

        # Get predictions
        py_predictions = svr.predict(self.lesmat_scaled)
        r_predictions = self.data['predictions_sklearn_defaults']

        # Predictions should be highly correlated
        corr, pval = pearsonr(py_predictions, r_predictions)

        print(f"\nPrediction correlation (linear, C=1): {corr:.6f}")
        print(f"P-value: {pval:.2e}")

        # Both use libsvm, so correlation should be very high (>0.99)
        assert corr > 0.99, (
            f"Prediction correlation {corr:.4f} is too low. "
            "Expected >0.99 for identical libsvm implementations."
        )

    def test_predictions_correlation_linear_c30(self):
        """Test Python SVR with R's default cost=30."""
        svr = SVR(kernel='linear', C=30.0, epsilon=0.1)
        svr.fit(self.lesmat_scaled, self.behavior_scaled)

        py_predictions = svr.predict(self.lesmat_scaled)
        r_predictions = self.data['predictions_linear']

        corr, pval = pearsonr(py_predictions, r_predictions)

        print(f"\nPrediction correlation (linear, C=30): {corr:.6f}")

        assert corr > 0.99, (
            f"Prediction correlation {corr:.4f} is too low."
        )

    def test_weights_correlation_linear(self):
        """Test that weight vectors are highly correlated.

        For linear kernel, weights can be extracted directly.
        """
        svr = SVR(kernel='linear', C=1.0, epsilon=0.1)
        svr.fit(self.lesmat_scaled, self.behavior_scaled)

        # Extract weights (sklearn stores as coef_ for linear kernel)
        py_weights = svr.coef_.flatten()
        r_weights = self.data['weights_sklearn_defaults']

        # Weights should be highly correlated
        corr, pval = pearsonr(py_weights, r_weights)

        print(f"\nWeight correlation (linear, C=1): {corr:.6f}")
        print(f"Python weights range: [{py_weights.min():.4f}, {py_weights.max():.4f}]")
        print(f"R weights range: [{r_weights.min():.4f}, {r_weights.max():.4f}]")

        # Weights should correlate very highly
        assert corr > 0.99, (
            f"Weight correlation {corr:.4f} is too low. "
            "Linear SVR weights should match closely."
        )

    def test_weights_magnitude_similar(self):
        """Test that weight magnitudes are in the same range."""
        svr = SVR(kernel='linear', C=1.0, epsilon=0.1)
        svr.fit(self.lesmat_scaled, self.behavior_scaled)

        py_weights = svr.coef_.flatten()
        r_weights = self.data['weights_sklearn_defaults']

        # Check that max absolute values are within 10% of each other
        py_max = np.max(np.abs(py_weights))
        r_max = np.max(np.abs(r_weights))

        ratio = py_max / r_max if r_max > 0 else float('inf')

        print(f"\nMax weight magnitude - Python: {py_max:.6f}, R: {r_max:.6f}")
        print(f"Ratio: {ratio:.4f}")

        assert 0.9 < ratio < 1.1, (
            f"Weight magnitude ratio {ratio:.4f} is outside expected range [0.9, 1.1]"
        )

    def test_prediction_accuracy_similar(self):
        """Test that prediction accuracy (correlation with behavior) is similar."""
        svr = SVR(kernel='linear', C=1.0, epsilon=0.1)
        svr.fit(self.lesmat_scaled, self.behavior_scaled)

        py_predictions = svr.predict(self.lesmat_scaled)

        # Correlation with true behavior
        py_corr, _ = pearsonr(py_predictions, self.behavior_scaled)
        r_corr, _ = pearsonr(
            self.data['predictions_sklearn_defaults'],
            self.behavior_scaled
        )

        print(f"\nPrediction-behavior correlation:")
        print(f"  Python: {py_corr:.6f}")
        print(f"  R:      {r_corr:.6f}")
        print(f"  Difference: {abs(py_corr - r_corr):.6f}")

        # Correlations should be very close
        assert abs(py_corr - r_corr) < 0.01, (
            f"Prediction accuracy differs by {abs(py_corr - r_corr):.4f}"
        )


class TestSVRImplementationDetails:
    """Test implementation details of the Python SVR."""

    def test_weight_extraction_linear_kernel(self):
        """Verify weight extraction for linear kernel matches formula."""
        np.random.seed(42)
        X = np.random.randn(20, 50)
        y = np.random.randn(20)

        svr = SVR(kernel='linear', C=1.0)
        svr.fit(X, y)

        # For linear kernel, coef_ should equal sum of alpha_i * x_i
        # where alpha_i are the dual coefficients
        weights_from_coef = svr.coef_.flatten()

        # Manual calculation: w = sum(dual_coef * support_vectors)
        weights_manual = np.dot(svr.dual_coef_, svr.support_vectors_).flatten()

        np.testing.assert_allclose(
            weights_from_coef, weights_manual, rtol=1e-10,
            err_msg="Weight extraction methods should match for linear kernel"
        )

    def test_scaling_consistency(self):
        """Test that scaling matches R's scale() function."""
        np.random.seed(42)
        x = np.random.randn(20)

        # Python scaling (matching R's scale with scale=T, center=T)
        x_scaled_py = (x - np.mean(x)) / np.std(x, ddof=0)

        # R uses n in denominator for scale() by default (ddof=0)
        # Verify our implementation is correct
        expected_mean = 0.0
        expected_std = 1.0

        assert abs(np.mean(x_scaled_py)) < 1e-10
        # Note: std will be slightly less than 1 due to centering
        assert abs(np.std(x_scaled_py, ddof=0) - 1.0) < 1e-10


class TestSVRDocumentation:
    """Document expected differences between R and Python SVR."""

    def test_document_parameter_differences(self):
        """Document the default parameter differences."""
        differences = {
            "kernel": {
                "R_default": "radial",
                "Python_default": "linear",
                "note": "R uses RBF kernel by default, Python uses linear"
            },
            "cost_C": {
                "R_default": 30,
                "Python_default": 1.0,
                "note": "R uses much higher regularization by default"
            },
            "gamma": {
                "R_default": 5,
                "Python_default": "scale (1/(n_features * X.var()))",
                "note": "Only applies to RBF kernel"
            },
            "epsilon": {
                "R_default": 0.1,
                "Python_default": 0.1,
                "note": "Same default"
            },
            "data_scaling": {
                "R": "Manual scale() before SVR",
                "Python": "Should add manual scaling to match R",
                "note": "R lsm_svr scales both lesmat and behavior"
            },
            "weight_scaling": {
                "R": "Scales by 10/max(abs(w))",
                "Python": "No scaling (returns raw weights)",
                "note": "R normalizes weights to [-10, 10] range"
            },
            "permutation_pvalues": {
                "R": "Built-in (default 10,000 permutations)",
                "Python": "Not implemented",
                "note": "R computes p-values via permutation testing"
            }
        }

        print("\n" + "="*60)
        print("EXPECTED DIFFERENCES: R (e1071) vs Python (sklearn) SVR")
        print("="*60)

        for param, info in differences.items():
            print(f"\n{param}:")
            for key, value in info.items():
                print(f"  {key}: {value}")

        # This test always passes - it's just for documentation
        assert True


if __name__ == "__main__":
    # Run tests with verbose output
    pytest.main([__file__, "-v", "-s"])
